import {
  AgendaEvent,
  EVENT_MODE,
  PUBLICATION_STATUS,
  TRANSLATION_STATUS,
  createEmptyAgendaEvent
} from '../models/agenda.models';

const emptyExtras = () => {
  const e = createEmptyAgendaEvent();
  return {
    organizerEs: e.organizerEs,
    organizerEn: e.organizerEn,
    speakerEs: e.speakerEs,
    speakerEn: e.speakerEn,
    audienceEs: e.audienceEs,
    audienceEn: e.audienceEn,
    ctaLabelEs: e.ctaLabelEs,
    ctaLabelEn: e.ctaLabelEn,
    ctaUrl: e.ctaUrl
  };
};

export const MOCK_AGENDA_EVENTS: AgendaEvent[] = [
  {
    id: 8001,
    titleEs: 'Jornada de divulgación científica',
    summaryEs: 'Actividades abiertas al público sobre investigación marina.',
    descriptionEs: '<p>Programa completo de charlas y talleres para toda la familia.</p>',
    titleEn: 'Science outreach day',
    summaryEn: 'Open activities on marine research for the general public.',
    descriptionEn: '<p>Full programme of talks and workshops for all ages.</p>',
    mainImageUrl: '',
    mainImageAltEs: 'Jornada de divulgación',
    mainImageAltEn: 'Outreach day',
    categories: [{ id: 'cat-events', label: 'Events', slug: 'events' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.PUBLISHED,
    translationStatus: TRANSLATION_STATUS.VALIDATED,
    eventDate: '2026-09-15',
    startTime: '10:00',
    endTime: '18:00',
    location: 'Auditorio principal',
    eventMode: EVENT_MODE.IN_PERSON,
    onlineUrl: '',
    organizerEs: 'Fundación Ciencia & Vida',
    organizerEn: 'Ciencia & Vida Foundation',
    speakerEs: 'Dra. María López',
    speakerEn: 'Dr. María López',
    audienceEs: 'Público general',
    audienceEn: 'General public',
    ctaLabelEs: 'Inscribirse',
    ctaLabelEn: 'Register',
    ctaUrl: 'https://example.org/register/outreach-day',
    slug: 'jornada-divulgacion-cientifica',
    metaTitle: 'Jornada de divulgación científica',
    metaDescription: 'Actividades abiertas al público sobre investigación marina.',
    ogTitle: 'Jornada de divulgación científica',
    ogDescription: 'Actividades abiertas al público sobre investigación marina.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/jornada-divulgacion-cientifica',
    featured: true,
    publishedAt: '2026-01-10',
    translationValidatedAt: '2026-01-08T10:00:00'
  },
  {
    id: 8002,
    titleEs: 'Seminario online de oceanografía',
    summaryEs: 'Sesión virtual con investigadores invitados.',
    descriptionEs: '<p>Seminario mensual sobre tendencias en oceanografía.</p>',
    titleEn: 'Online oceanography seminar',
    summaryEn: 'Virtual session with guest researchers.',
    descriptionEn: '<p>Monthly seminar on oceanography trends.</p>',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-seminars', label: 'Seminars', slug: 'seminars' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.READY_TO_PUBLISH,
    translationStatus: TRANSLATION_STATUS.VALIDATED,
    eventDate: '2026-11-20',
    startTime: '16:30',
    endTime: '18:00',
    location: '',
    eventMode: EVENT_MODE.ONLINE,
    onlineUrl: 'https://example.org/live/oceanography-seminar',
    ...emptyExtras(),
    slug: 'seminario-online-oceanografia',
    metaTitle: 'Seminario online de oceanografía',
    metaDescription: 'Sesión virtual con investigadores invitados.',
    ogTitle: 'Seminario online de oceanografía',
    ogDescription: 'Sesión virtual con investigadores invitados.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/seminario-online-oceanografia',
    featured: false,
    translationValidatedAt: '2026-02-01T12:00:00'
  },
  {
    id: 8003,
    titleEs: 'Taller híbrido de metodología',
    summaryEs: 'Borrador de evento formativo presencial y en línea.',
    descriptionEs: '<p>Contenido del taller en preparación.</p>',
    titleEn: '',
    summaryEn: '',
    descriptionEn: '',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-workshops', label: 'Workshops', slug: 'workshops' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.DRAFT,
    translationStatus: TRANSLATION_STATUS.NO_TRANSLATION,
    eventDate: '2026-12-05',
    startTime: '09:00',
    endTime: '13:00',
    location: 'Sala B',
    eventMode: EVENT_MODE.HYBRID,
    onlineUrl: 'https://example.org/live/methodology-workshop',
    ...emptyExtras(),
    slug: 'taller-hibrido-metodologia',
    metaTitle: '',
    metaDescription: '',
    ogTitle: '',
    ogDescription: '',
    ogImageUrl: '',
    publicUrl: '',
    featured: false
  },
  {
    id: 8004,
    titleEs: 'Conferencia anual (archivada)',
    summaryEs: 'Evento del año pasado, ya finalizado.',
    descriptionEs: '<p>Resumen del evento celebrado el año anterior.</p>',
    titleEn: 'Annual conference (archived)',
    summaryEn: 'Past event from last year.',
    descriptionEn: '<p>Summary of the event held last year.</p>',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-events', label: 'Events', slug: 'events' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.UNPUBLISHED,
    translationStatus: TRANSLATION_STATUS.AUTO_GENERATED,
    eventDate: '2025-06-01',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Campus central',
    eventMode: EVENT_MODE.IN_PERSON,
    onlineUrl: '',
    ...emptyExtras(),
    slug: 'conferencia-anual-archivada',
    metaTitle: 'Conferencia anual',
    metaDescription: 'Evento del año pasado.',
    ogTitle: 'Conferencia anual',
    ogDescription: 'Evento del año pasado.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/conferencia-anual-archivada',
    featured: false,
    publishedAt: '2025-05-01'
  }
];
