import {
  AgendaEvent,
  EVENT_MODE,
  PUBLICATION_STATUS,
  TRANSLATION_STATUS
} from '../models/agenda.models';

export const MOCK_AGENDA_EVENTS: AgendaEvent[] = [
  {
    id: 8001,
    titleEs: 'Jornada de divulgación científica',
    descriptionEs: '<p>Programa completo de charlas y talleres para toda la familia.</p>',
    titleEn: 'Science outreach day',
    descriptionEn: '<p>Full programme of talks and workshops for all ages.</p>',
    mainImageUrl: '',
    mainImageAltEs: 'Jornada de divulgación',
    mainImageAltEn: 'Outreach day',
    categories: [{ id: 'cat-events', label: 'Events', slug: 'events' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.PUBLISHED,
    translationStatus: TRANSLATION_STATUS.VALIDATED,
    eventDate: '2026-09-15',
    startTime: '10:00',
    endTime: '18:00',
    location: 'Auditorio principal',
    eventMode: EVENT_MODE.IN_PERSON,
    onlineUrl: '',
    slug: 'jornada-divulgacion-cientifica',
    metaTitle: 'Jornada de divulgación científica',
    metaDescription: 'Programa completo de charlas y talleres para toda la familia.',
    ogTitle: 'Jornada de divulgación científica',
    ogDescription: 'Programa completo de charlas y talleres para toda la familia.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/jornada-divulgacion-cientifica',
    featured: true,
    publishedAt: '2026-01-10',
    translationValidatedAt: '2026-01-08T10:00:00'
  },
  {
    id: 8002,
    titleEs: 'Seminario online de oceanografía',
    descriptionEs: '<p>Seminario mensual sobre tendencias en oceanografía.</p>',
    titleEn: 'Online oceanography seminar',
    descriptionEn: '<p>Monthly seminar on oceanography trends.</p>',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-seminars', label: 'Seminars', slug: 'seminars' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.READY_TO_PUBLISH,
    translationStatus: TRANSLATION_STATUS.VALIDATED,
    eventDate: '2026-11-20',
    startTime: '16:30',
    endTime: '18:00',
    location: '',
    eventMode: EVENT_MODE.ONLINE,
    onlineUrl: 'https://example.org/live/oceanography-seminar',
    slug: 'seminario-online-oceanografia',
    metaTitle: 'Seminario online de oceanografía',
    metaDescription: 'Seminario mensual sobre tendencias en oceanografía.',
    ogTitle: 'Seminario online de oceanografía',
    ogDescription: 'Seminario mensual sobre tendencias en oceanografía.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/seminario-online-oceanografia',
    featured: false,
    translationValidatedAt: '2026-02-01T12:00:00'
  },
  {
    id: 8003,
    titleEs: 'Taller híbrido de metodología',
    descriptionEs: '<p>Contenido del taller en preparación.</p>',
    titleEn: '',
    descriptionEn: '',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-workshops', label: 'Workshops', slug: 'workshops' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.DRAFT,
    translationStatus: TRANSLATION_STATUS.NO_TRANSLATION,
    eventDate: '2026-12-05',
    startTime: '09:00',
    endTime: '13:00',
    location: 'Sala B',
    eventMode: EVENT_MODE.HYBRID,
    onlineUrl: 'https://example.org/live/methodology-workshop',
    slug: 'taller-hibrido-metodologia',
    metaTitle: '',
    metaDescription: '',
    ogTitle: '',
    ogDescription: '',
    ogImageUrl: '',
    publicUrl: '',
    featured: false
  },
  {
    id: 8004,
    titleEs: 'Conferencia anual (archivada)',
    descriptionEs: '<p>Resumen del evento celebrado el año anterior.</p>',
    titleEn: 'Annual conference (archived)',
    descriptionEn: '<p>Summary of the event held last year.</p>',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    categories: [{ id: 'cat-events', label: 'Events', slug: 'events' }],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.UNPUBLISHED,
    translationStatus: TRANSLATION_STATUS.AUTO_GENERATED,
    eventDate: '2025-06-01',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Campus central',
    eventMode: EVENT_MODE.IN_PERSON,
    onlineUrl: '',
    slug: 'conferencia-anual-archivada',
    metaTitle: 'Conferencia anual',
    metaDescription: 'Evento del año pasado.',
    ogTitle: 'Conferencia anual',
    ogDescription: 'Evento del año pasado.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/agenda/conferencia-anual-archivada',
    featured: false,
    publishedAt: '2025-05-01'
  }
];
