import { NewsItem, PUBLICATION_STATUS, TRANSLATION_STATUS } from '../models/news.models';

export const MOCK_NEWS_ITEMS: NewsItem[] = [
  {
    id: 9001,
    titleEs: 'Avances en investigación marina',
    summaryEs: 'Resumen de los principales hallazgos del último trimestre.',
    bodyEs: '<p>Contenido de ejemplo en español.</p>',
    titleEn: 'Advances in marine research',
    summaryEn: 'Summary of the main findings from the last quarter.',
    bodyEn: '<p>Sample content in English.</p>',
    mainImageUrl: '',
    mainImageAltEs: 'Investigación marina',
    mainImageAltEn: 'Marine research',
    tags: [{ id: 'tag-1', label: 'Research', slug: 'research' }],
    categories: [{ id: 'cat-research', label: 'Research', slug: 'research' }],
    relatedPosts: [],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.PUBLISHED,
    translationStatus: TRANSLATION_STATUS.VALIDATED,
    publicationDate: '2025-03-15',
    slug: 'avances-investigacion-marina',
    metaTitle: 'Avances en investigación marina',
    metaDescription: 'Resumen de los principales hallazgos del último trimestre.',
    ogTitle: 'Avances en investigación marina',
    ogDescription: 'Resumen de los principales hallazgos del último trimestre.',
    ogImageUrl: '',
    publicUrl: 'https://example.org/news/avances-investigacion-marina',
    mediaLink: 'https://example.org/news/avances-investigacion-marina',
    featured: true,
    publishedAt: '2025-03-15',
    translationValidatedAt: '2025-03-10T10:00:00',
    numVisitas: 120,
    numLikes: 8
  },
  {
    id: 9002,
    titleEs: 'Borrador: evento de divulgación',
    summaryEs: 'Noticia en preparación.',
    bodyEs: '<p>Borrador del cuerpo.</p>',
    titleEn: '',
    summaryEn: '',
    bodyEn: '',
    mainImageUrl: '',
    mainImageAltEs: '',
    mainImageAltEn: '',
    tags: [],
    categories: [],
    relatedPosts: [],
    author: 'editor',
    publicationStatus: PUBLICATION_STATUS.DRAFT,
    translationStatus: TRANSLATION_STATUS.NO_TRANSLATION,
    publicationDate: null,
    slug: 'borrador-evento-divulgacion',
    metaTitle: '',
    metaDescription: '',
    ogTitle: '',
    ogDescription: '',
    ogImageUrl: '',
    publicUrl: '',
    mediaLink: '',
    featured: false
  }
];
